version: "3"
containers:
- name: cloud-client
  image: gcr.io/instruqt/cloud-client
  shell: /bin/bash
  ports:
  - 80
virtualbrowsers:
- name: console-openshift-console
  url: https://console-openshift-console.apps.ocp.proxy.${_SANDBOX_ID}.instruqt.io
virtualmachines:
- name: bastion
  image: rhel-cloud/rhel-9
  shell: /bin/bash
  environment:
    TF_VAR_pull_secret: 
  machine_type: n2d-standard-2
- name: proxy
  image: rhel-cloud/rhel-9
  shell: /bin/bash
  machine_type: n2d-standard-2
  allow_external_ingress:
  - http
  - https
  - high-ports
  provision_ssl_certificate: true
azure_subscriptions:
- name: rh-openshift-sandbox-azure
  roles:
  - Contributor
  - User Access Administrator
