#!/bin/bash
set -eo pipefail

az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
az account set --subscription $ARM_SUBSCRIPTION_ID

pushd /opt/openshift

mkdir -p cluster/conf
git clone https://github.com/benemon/rh-openshift-sandbox-instruqt-resources.git


echo "export TF_VAR_resource_group=$INSTRUQT_PARTICIPANT_ID" >> /etc/profile.d/instruqt-env.sh
echo "export TF_VAR_region=uksouth" >> /etc/profile.d/instruqt-env.sh
if [ -z "${INSTRUQT_PARTICIPANTS_DNS}" ]; then
    echo "INSTRUQT_PARTICIPANTS_DNS is unset"
    echo "export TF_VAR_base_domain=$INSTRUQT_PARTICIPANT_ID.env.play.instruqt.com" >> /etc/profile.d/instruqt-env.sh
else
    echo "export TF_VAR_base_domain=$INSTRUQT_PARTICIPANT_ID.$INSTRUQT_PARTICIPANTS_DNS" >> /etc/profile.d/instruqt-env.sh
fi
echo "export TF_VAR_cluster_name=ocp" >> /etc/profile.d/instruqt-env.sh
echo "export TF_VAR_arm_client_id=$ARM_CLIENT_ID" >> /etc/profile.d/instruqt-env.sh
echo "export TF_VAR_arm_client_secret=$ARM_CLIENT_SECRET" >> /etc/profile.d/instruqt-env.sh
echo "export TF_VAR_arm_tenant_id=$ARM_TENANT_ID" >> /etc/profile.d/instruqt-env.sh
echo "export TF_VAR_arm_subscription_id=$ARM_SUBSCRIPTION_ID" >> /etc/profile.d/instruqt-env.sh

source /etc/profile.d/instruqt-env.sh

pushd rh-openshift-sandbox-instruqt-resources/terraform/dns

terraform init
terraform apply -auto-approve

popd

pushd rh-openshift-sandbox-instruqt-resources/terraform/templates

terraform init
terraform apply -auto-approve

cp output/osServicePrincipal.json.tpl ~/.azure/osServicePrincipal.json
cp output/install-config.yaml.tpl /opt/openshift/cluster/conf/install-config.yaml

popd

pushd cluster

exit 0