#!/bin/bash
set -eo pipefail

az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
az account set --subscription $ARM_SUBSCRIPTION_ID

source /etc/profile.d/instruqt-env.sh

pushd /opt/openshift/cluster

exit 0